### ISSUE TITLE
Shutdown procedure for local testing

### ISSUE THREAD

**Issue by fabianfett** [swift-server/swift-aws-lambda-runtime#121]
In a non-trivial Lambda we might use an AHC, which we initialize with a factory method like this:

```swift
class MyLambdaHandler: EventLoopLambdaHandler {
    typealias In = SQS.Event
    typealias Out = Void

    let httpClient: HTTPClient

    static func create(_ eventLoop: EventLoop) -> EventLoopFuture<ByteBufferLambdaHandler> {
        let httpClient = HTTPClient(eventLoopGroupProvider: .shared(eventLoop))
        return eventLoop.makeSucceededFuture(MyLambdaHandler(httpClient: httpClient))
    }

    private init(httpClient: HTTPClient) {
        self.httpClient = httpClient
    }

    func handle(context: Lambda.Context, payload: SQS.Event) -> EventLoopFuture<Void> {
        // not interesting
    }
}

Lambda.run(MyLambdaHandler.create)
```

We currently don't have any chance to stop the `httpClient` in a coordinated way, if we stop the `LocalTestServer`, which closes the Lambda.

This is why I propose the following:

We expand the `ByteBufferLambdaHandler` protocol with a function `syncShutdown() throws` which will be invoked, if the Lambda is stopped. We supply a default empty implementation so that developers only need to deal with it if they run into a problem.

@tomerd @weissi @ktoso @adam-fowler wdyt?

**Comment by adam-fowler** [comment]
In the SNS to Slack example I posted I had to make the Lambda a class and shutdown the HTTPClient in the `deinit`. It would be cleaner if we could do it inside a `syncShutdown`.

**Comment by weissi** [comment]
That sounds like a great and necessary addition. Forcing people to do lifecycle management in `deinit` will lead to really bad problems further down the line.

**Comment by tomerd** [comment]
+1 good catch

**Comment by ktoso** [comment]
Approach sounds good @fabianfett  👍
