### ISSUE TITLE
Remove `lifecycleIteration` from Logger Metadata

### ISSUE THREAD

**Issue by fabianfett** [swift-server/swift-aws-lambda-runtime#123]
Currently we store a `lifecycleIteration` in the Logger metadata. For me this is always `0` on Lambda. I wonder if we should remove it...

**Comment by tomerd** [comment]
@fabianfett it is designed to increments to reflect the number of time the lambda gets invoked. the idea for it was to help troubleshoot things like memory bloat, but providing an easy way to include in the log what invocation number this was. if aws already provides this data maybe we can drop it

**Comment by fabianfett** [comment]
Oh shoot. I should invoke my lambdas more than once. 😉
