### ISSUE TITLE
Question/Request: Make HTTP requests

### ISSUE THREAD

**Issue by cardoso** [swift-server/swift-aws-lambda-runtime#149]
Can you make HTTP requests with this? Eg. to respond to a webhook, integrate APIs

I see there's the `HTTPClient`, which looks like it does HTTP requests, but it's currently `internal`.

**Comment by ktoso** [comment]
You can use the https://github.com/swift-server/async-http-client library 👍 

We're also working towards instrumenting it for tracing (with the swift-tracing instrumentation efforts), so it'd automatically carry XRay tracing headers as well 👍

**Comment by cardoso** [comment]
Thanks a lot @ktoso :)

**Comment by fabianfett** [comment]
@cardoso if you are more familiar with `URLSession` you can also just use it. Just make sure to `import FoundationNetworking` on Linux to get access to `URLSession`.

**Comment by cardoso** [comment]
That's even better. Thank you @fabianfett

**Comment by fabianfett** [comment]
@cardoso an example for you: https://github.com/swift-server/swift-aws-lambda-runtime/blob/master/Examples/LambdaFunctions/Sources/CurrencyExchange/main.swift
