### ISSUE TITLE
Database support?

### ISSUE THREAD

**Issue by crspybits** [swift-server/swift-aws-lambda-runtime#165]
Hi-- I am really appreciative of this effort for Swift AWS lambda support! Thanks so much.

Please take the following question in that appreciative light and also with the fact that I'm new to AWS lambda and not fully sure of the way it works.

I am wondering if database support will (eventually) be part of this effort or part of some other package? E.g., could one just use database access within Swift AWS lambda code from say `Vapor` (https://github.com/vapor/vapor) with the swift-aws-lambda-runtime package or would that support have to be tailored to AWS lambda?

Thanks!
Chris.

**Comment by MoridinBG** [comment]
You can use the db directly with https://github.com/vapor/sql-kit and one of the available drivers. I have good success with postgres-kit and a PostgreSQL in Amazon RDS accessed from Swift lambdas.

Fluent is higher level ORM on top of sql-kit and the drivers. You can try that too - https://github.com/vapor/fluent-kit

**Comment by crspybits** [comment]
Nice! Thanks!

**Comment by fabianfett** [comment]
I've also used vapor's [mysql-kit](https://github.com/vapor/mysql-kit) with Lambda. 

You could also use the DynamoDB client from the [aws-sdk-swift](https://github.com/swift-aws/aws-sdk-swift), if you want to use something serverless.

Does this solve your problem? Can we close this issue?

**Comment by crspybits** [comment]
Yes-- thanks. Closing.
