### ISSUE TITLE
Problem getting message from SQS in the lambda

### ISSUE THREAD

**Issue by jimadamsss** [swift-server/swift-aws-lambda-runtime#179]
I have created a lambda to read json requests sent in as the body element. This is something I have done previously using a lava based lambda but I wanted to try this with Swift. My issue is that my lambda fails when the message comes in due to a missing messageId. Once this happens the lambda is in a infinite loop attempting to read the same message over and over.

This is the error from Cloudwatch
2020-12-11T23:20:35+0000 warning Lambda : lifecycleIteration=0 lambda handler returned an error: requestDecoding(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "messageId", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"messageId\", intValue: nil) (\"messageId\").", underlyingError: nil)))

### Expected behavior
What I expect to happen is the lambda to fail with an error that stops the lambda from firing again. Secondly I would like to see the raw string so this can be debugged.

This was run using Swift 5.2 and swift lambda runtime version 0.3.0

**Comment by fabianfett** [comment]
Hi @jimadamsss,

are you sure you use an `SQS.Event` in your function signature? An `SQS.Event` is the container you receive when listening for `SQS.Messages`.

This code from the README is false:
```swift
// Import the modules
import AWSLambdaRuntime
import AWSLambdaEvents

// In this example we are receiving an SQS Message, with no response (Void).
Lambda.run { (context, message: SQS.Message, callback: @escaping (Result<Void, Error>) -> Void) in
  ...
  callback(.success(Void()))
}
```

It should be:
```swift
// Import the modules
import AWSLambdaRuntime
import AWSLambdaEvents

// In this example we are receiving an SQS Event, with no response (Void).
Lambda.run { (context, message: SQS.Event, callback: @escaping (Result<Void, Error>) -> Void) in
  ...
  callback(.success(Void()))
}
```

We are happy to receive prs to fix it.

**Comment by jimadamsss** [comment]
I will give it a try!

**Comment by jimadamsss** [comment]
I was able to get this to work

**Comment by mattmassicotte** [comment]
Same thing happened to me, here's PR to address it. Thanks @fabianfett for the explanation - you did all the work here :)

https://github.com/swift-server/swift-aws-lambda-runtime/pull/181

**Comment by tomerd** [comment]
@mattmassicotte @jimadamsss okay to close since #181 is merged?

**Comment by jimadamsss** [comment]
Fine with me!
