### ISSUE TITLE
How to view log messages

### ISSUE THREAD

**Issue by Peter-Schorn** [swift-server/swift-aws-lambda-runtime#180]
I'm having a little trouble figuring out how to see the logs for my function. Within my lambda function, at the very beginning, I have the following:

```swift
Lambda.run { (
    context: Lambda.Context,
    request: APIGateway.V2.Request,
    callback: @escaping (Result<APIGateway.V2.Response, Error>) -> Void
) in
    
    let message = "redirectURI: \(redirectURI); " +
        "rawQueryString: \(request.rawQueryString)"
    print(message)
    context.logger.error("\(message)")

    // ...

}
```

I also set the `LOG_LEVEL` environment variable to `trace`.

I went to the cloud watch console, as described in the [user guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#ViewingLogData) and selected "Log Groups" from the navigation pane and selected the log group for my function. Yet, I do not see any of the log messages that I created.

<img width="1422" alt="Screen Shot 2020-12-22 at 8 55 41 PM" src="https://user-images.githubusercontent.com/58197311/102953953-100df500-4498-11eb-8319-d760641e3e62.png">

I apologize if this is the wrong place to ask this question, but I could not find any helpful information anywhere else.

**Comment by tomerd** [comment]
@Peter-Schorn sorry for the slow response. logging with context.logger.error should work out of the box. are you still experiencing this issue?

**Comment by Peter-Schorn** [comment]
Thanks for your response. I am no longer experiencing any issues. I discovered that it takes 5-10 minutes for log messages to show up in the cloud watch console.

**Comment by fabianfett** [comment]
@Peter-Schorn Do you mind of we close this issue now?
