### ISSUE TITLE
Will support customization of JSONDecoder?

### ISSUE THREAD

**Issue by WataruSuzuki** [swift-server/swift-aws-lambda-runtime#204]
Hi,

I am considering this library, however I found it difficult to use because `JSONDecoder` cannot be customized.
I would like to use like this :
```swift
Lambda.decoder.dateDecodingStrategy = .formatted(someDateFormatter)
Lambda.decoder.keyDecodingStrategy = .convertFromSnakeCase
```

Is there any reason why `defaultJSONDecoder` cannot be customized by users?
- https://github.com/swift-server/swift-aws-lambda-runtime/blob/19a9f92538c67cc8070c02a673e9417b07c34e3e/Sources/AWSLambdaRuntime/Lambda%2BCodable.swift#L122

If there's no particular reason, I'm thinking of I will write a patch.

Thank you!

**Comment by fabianfett** [comment]
Hi @WataruSuzuki,

you can already customize your `jsonDecoder`. However this is not really good documented. 

1. You need to use the `LambdaHandler` or `EventLoopLambdaHandler` protocol. 
2. You need to implement the method `func decode(buffer: ByteBuffer) throws -> In` which has a default implementation
3. In this method you can use your custom `jsonDecoder`.

Your final code will look something like this:

```swift
// important to get support for ByteBuffer in JSONDecoder
import NIOFoundationCompat

struct YourHandler: LambdaHandler {
  typealias In = YourInputType
  typealias Out = YourOutputType

  let jsonDecoder = Self.createJSONDecoder()

  func handle(context: Lambda.Context, event: In, callback: @escaping (Result<Out, Error>) -> Void) {
    // your implementation
  }

  // overwrite default implementation
  func decode(buffer: ByteBuffer) throws -> In {
    self.decoder.decode(In.self, from: buffer)
  }

  private static func createJSONDecoder() -> JSONDecoder { 
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .formatted(someDateFormatter)
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    return decoder
  }
}
```

Does that help you?

**Comment by WataruSuzuki** [comment]
Hi @fabianfett 

Thank you for tips.
It solves my issue!!
