### ISSUE TITLE
Remove callback based LambdaHandler

### ISSUE THREAD

**Issue by fabianfett** [swift-server/swift-aws-lambda-runtime#212]
We should remove the Callback LambdaHandler.

**Comment by saltzmanjoelh** [comment]
Hi, sorry to comment on an already closed issue. I wasn't sure if I should open a new issue or continue with this one? 

I noticed that the readme has the closure based examples. Do you want some help updating them? If so, would you like them to simply use the async `handle(event:context)` form like in `LambdaTestingTests.testCodableClosure`?

Thanks!
