### ISSUE TITLE
Compiler errors Xcode 13

### ISSUE THREAD

**Issue by lynchspin** [swift-server/swift-aws-lambda-runtime#234]
Disclaimer: I'm pretty new to swift lambdas, so this may be something silly on my end. But below is the issue I'm currently facing.

### Expected behavior
No compiler errors.

### Actual behavior
see image attached

### Steps to reproduce

Clone the latest repo, run the project on Mac with Xcode 13 installed.

### If possible, minimal yet complete reproducer code (or URL to code)

I cloned the repo and then attempted to test run samples. I didn't change any code. The errors appear in both the `LambdaHandler.swift` and `Lambda.swift` files. The hash I provide below refers to this test case, but I'm also seeing it in a project I'm building that references version `0.5.1` in the `Package.swift` file.

### SwiftAWSLambdaRuntime version/commit hash

011e8ddc4b1b02788a39d521f903eb27b6361c0b

### Swift & OS version (output of `swift --version && uname -a`)
Swift 5.5, Xcode 13, macOS Big Sur version 11.6
<img width="1266" alt="Screen Shot 2021-09-29 at 7 14 14 PM" src="https://user-images.githubusercontent.com/6817719/135376043-00a5c87d-3b72-43e7-9a47-6c1d1f4993b9.png">

**Comment by programmarchy** [comment]
You could compile with the Swift 5.4.3 toolchain until Swift 5.5 is supported.

Download it [here](https://swift.org/download/#releases) and set it in Xcode > Preferences > Toolchains

Looks like in Swift 5.5 the method was renamed to `completeWith`

**Comment by lynchspin** [comment]
I'll give that a shot. Thanks @programmarchy, I really appreciate it!
