### ISSUE TITLE
Question: Can swift-aws-lambda-runtime run on arm?

### ISSUE THREAD

**Issue by mufumade** [swift-server/swift-aws-lambda-runtime#235]
As of today [AWS lambda can now run using arm/gravaton2 architecture instead of x86.](https://aws.amazon.com/de/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) Is there any reason not to use arm for the swift-aws-lambda-runtime? 

According to AWS this would be a price reduction and a performance increase. And that's obviously something that we all want :) 

Thanks!

**Comment by fabianfett** [comment]
@mufumade Yes it can! You just need to compile it using the swift nightly amazonlinux2 arm64 toolchain/docker image.

**Comment by mufumade** [comment]
Alright. Thanks a lot for the quick answer :)
