### ISSUE TITLE
Licence is invalid

### ISSUE THREAD

**Issue by 0xTim** [swift-server/swift-aws-lambda-runtime#241]
The Apache licence added to the project does not contain a copyright year or name of the copyright holder - https://github.com/swift-server/swift-aws-lambda-runtime/blob/main/LICENSE.txt#L190

This should probably be fixed...

**Comment by fabianfett** [comment]
cc @tomerd

**Comment by tomerd** [comment]
same as swift-server/async-http-client#523 (comment)?

**Comment by 0xTim** [comment]
Yep
