### ISSUE TITLE
README.MD example about SimpleLambdaHandler 

### ISSUE THREAD

**Issue by fitomad** [swift-server/swift-aws-lambda-runtime#285]
The **README.MD** file contains an example about the use of `SimpleLambdaHandler` receiving an Amazon SQS event 

```swift
import AWSLambdaRuntime
import AWSLambdaEvents

@main
struct MyLambda: SimpleLambdaHandler {
    // In this example we are receiving a SQS Event, with no response (Void).
    func handle(_ event: SQS.Event, context: LambdaContext) async throws -> Void {
        ...
    }
}
```

There's no `SQS.Event` type available in the `AWSLambdaEvents` package, It seems that the expected type is [`SQSEvent`](https://github.com/swift-server/swift-aws-lambda-events/blob/main/Sources/AWSLambdaEvents/SQS.swift) 

```swift
import AWSLambdaRuntime
import AWSLambdaEvents

@main
struct MyLambda: SimpleLambdaHandler {
    // In this example we are receiving a SQS Event, with no response (Void).
    func handle(_ event: SQSEvent, context: LambdaContext) async throws {
        ...
    }
}
```

Also removed the returning `Void` following the Apple style guide, but I understand that is presented due to educational purpose.

**Comment by tomerd** [comment]
thanks @fitomad would you like to submit a PR to address this?

**Comment by fitomad** [comment]
Created a PR with code #286 😜

**Comment by tomerd** [comment]
thanks @fitomad
