### ISSUE TITLE
Debugging locally on a different invocation endpoint

### ISSUE THREAD

**Issue by jsonfry** [swift-server/swift-aws-lambda-runtime#320]
### Expected behavior

When debugging locally, you have to send POST requests to `/invoke`. 

I'm trying to use another [lambda local tool](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) that is expecting the invoke url to be `/2015-03-31/functions/function/invocations`, as per the "runtime interface emulator" described here https://docs.aws.amazon.com/lambda/latest/dg/images-test.html

### Actual behavior

As this runtime runs it locally on `/invoke` this of course does not work, and is not changeable

### Steps to reproduce

n/a

### What version of this project (`swift-aws-lambda-runtime`) are you using?

1.0.0-alpha.2

### Swift version

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
Darwin *** 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by jsonfry** [comment]
Would it be possible to have an environment variable that is picked up that allows the local server to use a different path? I could submit a PR for this.

**Comment by jsonfry** [comment]
I've been trying to see if the aws lambda client (which https://docs.aws.amazon.com/lambda/latest/dg/images-test.html is using) can be asked to use a completely different invoke endpoint, but the `2015-03-31/functions/*/invocations` part is baked in.

**Comment by sebsto** [comment]
Merged into main
https://github.com/swift-server/swift-aws-lambda-runtime/pull/321
