### ISSUE TITLE
Event JSON

### ISSUE THREAD

**Issue by RyPoints** [swift-server/swift-aws-lambda-runtime#324]
### Expected behavior

Received from a Lambda Event JSON test. The question is about how to get the Event JSON.
```
[SwiftCode] Received client context: nil
2024-05-05T22:50:14+0000 debug SwiftCode : [SwiftCode] Received client context: nil
2024-05-05T22:50:14+0000 error SwiftCode : [SwiftCode] Unknown event: 
{} Request(body: nil, rawQueryString: nil, httpMethod: nil, headers: nil, queryStringParameters: nil, 
pathParameters: nil, stageVariables: nil, isBase64Encoded: nil, eventSource: nil)
```
```
@main
struct SwiftCode: LambdaHandler {
    
    typealias Event = Request
    typealias Output = Response

    func handle(_ event: Request, context: LambdaContext) async throws -> Response {
    //Logging code
    }
}
```
 It works fine from the API Gateway, but how does one get the Lambda Event JSON?  

Perhaps changing the Request type will achieve this somehow, but often interfaces in other languages than Swift provide a method to both access the API Gateway Body and the Lambda Event JSON from the same Lambda handler structure.

### Actual behavior

Actual behavior is Lambda events seem to have no method to access Lambda Console Event JSON.

### Steps to reproduce

Log all variables when in the AWS Lambda Event JSON console and passing an event JSON.  All variables are nil.

### If possible, minimal yet complete reproducer code (or URL to code)

See above.

### What version of this project (`swift-aws-lambda-runtime`) are you using?

.package(url: "https://github.com/swift-server/swift-aws-lambda-runtime", branch: "main"),

### Swift version

5.10

### Amazon Linux 2 docker image version

Amazon Linux 2 (Karoo) and now Amazon Linux 2023.4.20240401 where it's also running fine.

**Comment by RyPoints** [comment]
Will take a look at your samples when I have a moment.  I'm looking at a V1 REST API and the Lambda Event JSON, so slightly different than the samples, but the answer might be in the samples if I review more.  Was attempting to construct some very general function that worked for all scenarios at once for verification.

**Comment by sebsto** [comment]
Hello @RyPoints 
You're correct, the example I gave above is for API Gateway v1.
There is a `struct` definition for API Gateway v1 also. Check [this file in the Lambda events project](https://github.com/swift-server/swift-aws-lambda-events/blob/main/Sources/AWSLambdaEvents/APIGateway.swift).

If you want to access the raw byte stream and be in charge of the decoding yourself, you can do that too.

Either you use the `SimpleLambdaHandler` with a `String` parameter, just like in this example 
https://github.com/swift-server/swift-aws-lambda-runtime/blob/main/Examples/Echo/Lambda.swift
Or you can implement a `ByteBufferLambdaHandler` that gives you access to the raw byte buffer from SwiftNIO

https://github.com/swift-server/swift-aws-lambda-runtime/blob/221978224cf82027f46c0aa54def83476fb74412/Sources/AWSLambdaRuntimeCore/LambdaHandler.swift#L401

**Comment by RyPoints** [comment]
Thanks for the additional info.  I will definitely take a look at that as well.  Like the dev over here.  Catching up.
