### ISSUE TITLE
Copy Resources from External Dependencies into Archived Zip

### ISSUE THREAD

**Issue by jrosen081** [swift-server/swift-aws-lambda-runtime#367]
### Expected behavior

When adding a third-party dependency, I would expect the zip file to correctly have the resources of _all_ dependencies.

### Actual behavior

When adding a 3rd party dependency (https://github.com/awslabs/aws-sdk-swift was what happened with me), the resources files for the dependencies were not added to the final zip. This caused an issue when trying to start up the lambda.

### Steps to reproduce

1. Follow this guide (https://fabianfett.dev/getting-started-with-swift-aws-lambda-runtime)
2. Add AWS SDK to project
3. Archive and upload to lambda
4. See failure on launch with fatalerror looking for resource bundle.

### What version of this project (`swift-aws-lambda-runtime`) are you using?

1.0.0-alpha-3

### Swift version

Swift 5.10

**Comment by jrosen081** [comment]
I was able to work around this by adding my own script which adds the needed resources to the zip file, but it would be great if it worked automatically.

**Comment by fabianfett** [comment]
We should fix this in the Packager. Do we need to go through all the dependencies and check if they have resources? I assume so.

**Comment by kkla320** [comment]
> I was able to work around this by adding my own script which adds the needed resources to the zip file, but it would be great if it worked automatically.

I am currently experiencing the same problem. Until there is a solution integrated into plugin. Could you share your solution here?

**Comment by jrosen081** [comment]
> We should fix this in the Packager plugin. Do we need to go through all the dependencies and check if they have resources? I assume so.

Yeah I think so. The resources get put automatically in `.build/release/{PACKAGE_NAME}.resources`, it likely needs to be copied into the final directory before zipping.

I have added these lines to my local script to make it work:
`sudo cp -r .build/release/aws-sdk-swift_AWSClientRuntime.resources .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/{PRODUCT_NAME}/`

**Comment by jrosen081** [comment]
@fabianfett I put up a pr here that I believe should fix it (testing locally works) https://github.com/swift-server/swift-aws-lambda-runtime/pull/386. Let me know what you think and what the next steps of the process are for pull requests!
