### ISSUE TITLE
Create a CI job that tests that we don't like full Foundation

### ISSUE THREAD

**Issue by fabianfett** [swift-server/swift-aws-lambda-runtime#402]
### Expected behavior

We should have a CI job that validates that we don't link full Foundation and only link FoundationEssentials.

### Actual behavior

N/A

### Steps to reproduce

N/A

### What version of this project (`swift-aws-lambda-runtime`) are you using?

N/A

### Swift version

N/A

**Comment by sebsto** [comment]
Work in progress on the event library 
https://github.com/swift-server/swift-aws-lambda-events/pull/81

**Comment by sebsto** [comment]
Fixed by https://github.com/swift-server/swift-aws-lambda-runtime/pull/441
