### ISSUE TITLE
error: Plugin ‘AWSLambdaPackager’ was denied permission to allow docker unix domain socket connections. 

### ISSUE THREAD

**Issue by djryanash** [swift-server/swift-aws-lambda-runtime#420]
### Expected behavior

After using `swift package --disable-sandbox archive` in the Terminal, I expected the command to create the AWS Lambda ZIP package.

### Actual behavior

The command `swift package --disable-sandbox archive` failed with an error:
```
Plugin ‘AWSLambdaPackager’ wants permission to allow docker unix domain socket connections.
Stated reason: “This plugin uses Docker to create the AWS Lambda ZIP package.”.
Allow this plugin to allow docker unix domain socket connections? (yes/no) y
error: Plugin was denied permission to allow docker unix domain socket connections.
```

### Steps to reproduce

I am following this talk [Swift, Server-Side, Serverless - Sébastien Stormacq](https://www.youtube.com/watch?v=M1POAEPATFo)

1. I created a package using swift CLI: `swift package init --type executable --name MyFinalLambdaFunction`
2. I opened the project in Xcode and added the dependencies:
```
let package = Package(
    name: "swict-aws-lambda-runtime-example",
    platforms: [
        .macOS(.v15)
    ],
    products: [
        .executable(name: "HttpApiLambda", targets: ["HttpApiLambda"])
    ],
    dependencies: [
        .package(url: "https://github.com/swift-server/swift-aws-lambda-runtime.git", branch: "main"),
        .package(url: "https://github.com/swift-server/swift-aws-lambda-events.git", branch: "main")
    ],
    targets: [
        .executableTarget(
            name: "HttpApiLambda",
            dependencies: [
                .product(name: "AWSLambdaRuntime", package: "swift-aws-lambda-runtime"),
                .product(name: "AWSLambdaEvents", package: "swift-aws-lambda-events"),
            ]
            //path: "./HttpApiLambda"
        )
    ]
)
```
3.  From Terminal, I built the project: `swift build --disable-sandbox`
4.  Then I ran `swift package --disable-sandbox archive` at which point I got the error.
5. I checked that AWS and Docker were correctly installed as well:
```
>> where aws
/usr/local/bin/aws
/usr/local/bin/aws
…/Documents/xcode-projects/MyFinalLambdaFunction via 🐦 v6.0 
>> where docker
/usr/local/bin/docker
/usr/local/bin/docker
…/Documents/xcode-projects/MyFinalLambdaFunction via 🐦 v6.0 
>> 
```

As a side note, I am also getting this in Xcode.
> invalid custom path './HttpApiLambda' for target 'HttpApiLambda'

### If possible, minimal yet complete reproducer code (or URL to code)

See code above to minimally reproduce.

### What version of this project (`swift-aws-lambda-runtime`) are you using?

1.0.0-alpha.3

### Swift version

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: x86_64-apple-macosx15.0
Darwin 2020-MacBook-Pro-Ryan.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:30 PDT 2024; root:xnu-11215.1.10~2/RELEASE_X86_64 x86_64

**Comment by sebsto** [comment]
@djryanash any news bout this ?

**Comment by sebsto** [comment]
I assume this error was due to a mix between using the runtime v1 and v2 semantic. 
I'm closing it for now, please feel free to reopen if you're still experiencing issues with this.
