### ISSUE TITLE
better representation for numeric sqs-message-attributes

### ISSUE THREAD

**Issue by tomerd** [swift-server/swift-aws-lambda-runtime#53]
https://github.com/swift-server/swift-aws-lambda-runtime/pull/46/files#diff-46c15e7ad33f3c55f1eff630cb7c7d6aR30

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html under "Message Attribute Data Types"

> Number attributes can store positive or negative numerical values. A number can have up to 38 digits of precision, and it can be between 10^-128 and 10^+126.

right now using string as a stop gap, could use Foundation's Decimal or come up with our own BigNumber abstraction

**Comment by sebsto** [comment]
Moved to Lambda event project 
https://github.com/swift-server/swift-aws-lambda-events/issues/53
